# Generated by Django 5.0.6 on 2024-07-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название мед.услуги"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание мед.услуги")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Превью мед.услуги",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена мед.услуги")),
                (
                    "deadline",
                    models.CharField(
                        max_length=100, verbose_name="Срок выполнения мед.услуги"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_services.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мед.услуга",
                "verbose_name_plural": "Мед.услуги",
            },
        ),
    ]
